#!/bin/sh
echo "---------------- Time for a repo update! -------------------"
echo "----------- Removing Existing Packages file... -------------"
rm -rv Packages.gz
echo "-------------------------- Done ----------------------------"
echo "-------------- Scanning for new packages... ----------------"
dpkg-scanpackages -m . /dev/null >Packages
echo "-------------------------- Done ----------------------------"
echo "------------ Applying the updated packages... --------------"
gzip Packages
echo "-------------------------- Done ----------------------------"
echo "----Repository updated. Go back to your drugs you hippy.----"
